### ISSUE TITLE
Error on make -j8 bzImage

### ISSUE THREAD

**Issue by cosmo-developer** [liva/minimal-linux#2]
/bin/sh: 1: bc: not found
make[1]: *** [Kbuild:42: include/generated/timeconst.h] Error 127
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1054: prepare0] Error 2
make: *** Waiting for unfinished jobs....
  HOSTLD  scripts/mod/modpost

**Comment by liva** [comment]
install "bc".
(e.g. `apt install bc` for Ubuntu/Debian)

**Comment by cosmo-developer** [comment]
## Yes It works.
